sources:
  bundler: true

allowed:
  - mit
  - apache-2.0

reviewed:
  bundler:
    # ruby license
    - base64
    - bigdecimal
    - json
    - pathname-common_prefix
    - securerandom

    # bsd-2 or ruby
    - byebug
    - csv
    - drb
    - io-console
    - logger
    - net-http
    - ostruct
    - racc
    - reline
    - ruby2_keywords
    - uri

    # mit, detected as other
    - concurrent-ruby
    - parser
    - ruby-progressbar

    # dwtfyw
    - reverse_markdown
