#!/bin/sh

set -e

BASE_PATH="$(CDPATH= cd "$(dirname "$0")/.." && pwd)"
if [ -f "$BASE_PATH/.licensed-dev-env" ]; then
	. "$BASE_PATH/.licensed-dev-env"
fi

bundle exec rake test
bundle exec rubocop -S -D
gem build licensed.gemspec
