#!/bin/bash
set -e

BASE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
. "$BASE_PATH/script/development-env"

if [ -z "$(which bower)" ]; then
  echo "A local bower installation is required for bower development." >&2
  exit 127
fi

# setup test fixtures
cd $BASE_PATH/test/fixtures/bower

if [ "$1" == "-f" ]; then
  git clean -ffX .
fi

bower install
