#!/bin/bash
set -e

# setup test fixtures
BASE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd $BASE_PATH/test/fixtures/git_submodule

if [ "$1" == "-f" ]; then
  git clean -ffX .
fi

FIXTURES="$(pwd)/nested $(pwd)/submodule $(pwd)/project"
SUBMODULE=""
echo "setting up git_submodule test fixtures"
for fixture in $FIXTURES; do
  mkdir -p $fixture
  pushd $fixture >/dev/null

  if [ ! -e ".git" ]; then
    git init -q .
    cp "$BASE_PATH/LICENSE" .
    git add LICENSE
    git commit -q -m "init"
  fi

  if [ -n "$SUBMODULE" ]; then
    if [ ! -e "vendor/$(basename "$SUBMODULE")/.git" ]; then
      git -c protocol.file.allow=always submodule add -q "$SUBMODULE" "vendor/$(basename "$SUBMODULE")"
    fi
    git -c protocol.file.allow=always submodule update --recursive --init -q
    if ! git diff --cached --quiet; then
      git commit -q -m "update submodule"
    fi
  fi

  echo "$(basename $fixture) created"

  SUBMODULE="$(pwd)"
  popd >/dev/null
done
